### ISSUE TITLE
In SAMP the following error is displayed - offset {54729464} - 0685: IS_OBJECT_ATTACHED

### ISSUE THREAD

**Issue by Jessyy** [cleolibrary/CLEO5#274]
Hello,

While in multiplayer ( SAMP ) by accessing the map menu the CLEO will start to displayed continuously the following error:
- https://www.youtube.com/watch?v=O0eTrp7_elM
- by exiting the map menu the user will no longer receive the error message
![Image](https://github.com/user-attachments/assets/0c6610c1-0ca5-437b-a648-4958266e7154)
![Image](https://github.com/user-attachments/assets/1268ffc4-4033-4530-a3c0-f2ba99de6d61)

Repro steps:
- Install the CLEO RC 3 version
- Open SAMP and connect to a server ( use this ip: samp.rss-ro.com:7777 )
- After the character is spawned access the map menu and remain idle
- Confirm each error message that will be displayed

I've also attached a cleo log, let me know if you need any additional info in order to reproduce it.
[.cleo.log](https://github.com/user-attachments/files/18551636/default.cleo.log)

**Comment by x87** [comment]
Thank you for the very detailed bug report!

**Comment by x87** [comment]
To quickly remediate the problem, open `CLEO\CLEO_PLUGINS\SA.DebugUtils.ini` and change Time to 0.

We will look into why the error gets triggered.

**Comment by MiranDMC** [comment]
Seems like SAMP runs some scripts despite of game pause, but why it makes time calculations invalid I have no idea. That will need further investigation.

**Comment by x87** [comment]
I think it calls opcodes using plugin-sdk using same thread id. Begin only called once, then after 5 seconds, CLEO starts thinking that this script is stuck, however in reality SAMP just executes one opcode at a time.

**Comment by x87** [comment]
@Jessyy can you do a quick test

update SA.DebugUtils.ini to the following
```
[Limits]
Command = 100
Time = 0
```

and see if there is another error message appearing while in the game menu with some interval (after each 100 commands executed)

**Comment by Jessyy** [comment]
yeap,

> To quickly remediate the problem, open `CLEO\CLEO_PLUGINS\SA.DebugUtils.ini` and change Time to 0.

by only changing this value, indeed the error message is no longer received ( I was ~2 min idle in the map menu and nothing )


> update SA.DebugUtils.ini to the following
> ```
> [Limits]
> Command = 100
> Time = 0
> ```

by changing both values, right after the gta-sa is booted 3 different error messages are received:
{56679} - 0004: SET_VAR_INT
![Image](https://github.com/user-attachments/assets/57d7d755-a3b3-4a46-bf7f-e05847cc3476)
{50194} - 0363: SET_VISIBILITY_OF_CLOSEST_OBJECT_OF_TYPE
![Image](https://github.com/user-attachments/assets/a50e34c3-6d97-4589-8ea0-f36fc9931571)
{66387} - 0005: SET_VAR_FLOAT
![Image](https://github.com/user-attachments/assets/ead5357f-ebae-481e-baf3-238620075385)

full log here - [.cleo.log](https://github.com/user-attachments/files/18551931/default.cleo.log)

after I confirm all the messages the game will remain on a black screen... but not stuck, will still respond when I press the ESC button
and if I start to smash the esc button a pink text can be seen for a split second on the left side corner
hopefully you can see it by changing the playback speed on - https://youtu.be/2ND6VGvODdw

**Comment by x87** [comment]
Yeah, 100 commands might be to low. Looks like CLEO suspended the main script which resulted in black screen (@MiranDMC , FYI. If there is only one active script, we should not lock it).

You may try setting some larger value, like 5000, so main scripts initialization works, but then menu scripts will not (once they hit 5k mark).

I guess the problem is clear now.

**Comment by Jessyy** [comment]
with the value set to 5000, the first behavior that was report is presented
I will be able to get spawn and logging into the server, once I access the map menu the error messages are received
[.cleo.log](https://github.com/user-attachments/files/18552005/default.cleo.log)

**Comment by x87** [comment]
Thanks!

**Comment by x87** [comment]
@MiranDMC I think we should ignore non-CLEO scripts. CLEO should not be responsible for any script running in game.

**Comment by x87** [comment]
@Jessyy can you update DebugUtils plugins using this build https://github.com/cleolibrary/CLEO5/actions/runs/12979381300/artifacts/2487903358  and see if it make any difference with original ini settings?

**Comment by MiranDMC** [comment]
Limiting features just to CLEO scripts makes no sense. So during development of main.scm any dead loop should lead to game crash?
Makes everything complicated from user view point forcing them to reading pages of documentation about exclusions, exceptions and special cases.

Problem is that apparently scripts created by Plugin SDK every single time are allocated at same address.
This is probably not SDK command call but some script callback executed from SAMP.

**Comment by x87** [comment]
> So during development of main.scm any dead loop should lead to game crash?

always has been. nothing new here.

**Comment by MiranDMC** [comment]
This won't fix problem if same callback is used in CLEO script.

**Comment by MiranDMC** [comment]
@Jessyy Can you please check if this build fixes the issue?
https://github.com/cleolibrary/CLEO5/actions/runs/12979744902/artifacts/2487984995
You can extract all files, or just replace **SA.DebugUtils.cleo** and **SA.DebugUtils.ini**

**Comment by Jessyy** [comment]
Hello,
In both tests I've used the config file from the archive ( the default one )

> [@Jessyy](https://github.com/Jessyy) can you update DebugUtils plugin from https://github.com/cleolibrary/CLEO5/actions/runs/12979381300/artifacts/2487903358 and see if it makes any difference with original ini settings?

yes, using this iteration I was not able to reproduce the issue
in my tests I was like ~3 minutes idle on two different servers where I knew the problem was reproducible and nothing :)
just in case, this is my last log - [.cleo-1.log](https://github.com/user-attachments/files/18564143/default.cleo-1.log)

> [@Jessyy](https://github.com/Jessyy) Can you please check if this build fixes the issue? https://github.com/cleolibrary/CLEO5/actions/runs/12979744902/artifacts/2487984995 You can extract all files, or just replace **SA.DebugUtils.cleo** and **SA.DebugUtils.ini**

bad news, the issue is still present with this iteration
Over 5 seconds of lag in a single frame by script 'main.scm' at offset {56433400} - 0685: IS_OBJECT_ATTACHED
![Image](https://github.com/user-attachments/assets/bf6d14b5-a830-43d3-80b5-f3a7ad578514)
log here - [.cleo-2.log](https://github.com/user-attachments/files/18564196/default.cleo-2.log)

---

I know that it's too late to mention now ( I don't know why I didn't do it in the first place ), this issue was first introduced in RC3 version; while using the older versions ( RC2 or RC1 ) the reported behavior cannot be reproduced :/

**Comment by x87** [comment]
> I know that it's too late to mention now ( I don't know why I didn't do it in the first place ), this issue was first introduced in RC3 version; while using the older versions ( RC2 or RC1 ) the reported behavior cannot be reproduced :/

this lag detection was added in RC3

**Comment by MiranDMC** [comment]
Hm we merged fix already, https://github.com/cleolibrary/CLEO5/actions/runs/12982429025/artifacts/2488575213
It is called once a render frame. Seems this does not work for you because something else sabotaged CLEO's on-render hook.
In the video I can see after error message there is no CLEO log messages at the screen.
@Jessyy in log file I can see you have several graphic related ASI plugins. Can you please disable them and try again with linked version?

**Comment by Jessyy** [comment]
Hello,

> In the video I can see after error message there is no CLEO log messages at the screen.
I've disabled several ASI plugin, now the CLEO log will be displayed in-game. If I'm not mistaken, for this behavior someone has already reported it here #266 

Just to make sure that the initial behavior that was reported is still the same, I've done a recheck with a clean version of RC3.
- same results, now with the screen log displayed https://youtu.be/qafTs2o5hvA
- log here [.cleo-0.log](https://github.com/user-attachments/files/18577372/default.cleo-0.log)

> Hm we merged fix already, https://github.com/cleolibrary/CLEO5/actions/runs/12982429025/artifacts/2488575213 
As for the new iteration:
👍  the fix seems to be working and I'm no longer receiving the mentioned errors
- log here [.cleo-1.log](https://github.com/user-attachments/files/18577540/default.cleo-1.log)
👎 pfff, by using the SA.Project2DFX mod will bring back the initial issue :/
- log here [.cleo-2.log](https://github.com/user-attachments/files/18579134/default.cleo-2.log)

**Comment by Jessyy** [comment]
update!!! regarding to my previous comment, especially the part about Project2DFX
I've used this iteration https://github.com/cleolibrary/CLEO5/actions/runs/13018740108/artifacts/2500005840 that was created 1h ago:
- I can confirm that now the screen log will be displayed
- Also, it will no longer affect the fix for this thread … I'm no longer receiving any errors in the map menu ( if the plan is to also include 'DrawingFinished hook updated' with the 'Fix scriptLog problems with script callbacks from SAMP' )

**Comment by MiranDMC** [comment]
Fixed.
